frame_id: map
initial_pose:
  x: 0.0
  y: 0.0
  yaw: 0.0

goals:
   desk:
    x: -0.03
    y: -2.20
    yaw: -1.94
  bed:
    x: 2.10
    y: 0.20
    yaw: 0.00
  kitchen:
    x: 0.30
    y: 1.80
    yaw: -1.57
