frame_id: map

# Optional but recommended for AMCL
initial_pose:
  x: 0.0
  y: 0.0
  yaw: 0.0

goals:
  desk: { x: 17.86, y: -0.77, yaw: 0.0 }
  bed: { x: 12.10, y: 3.05, yaw: 1.57 }
  kitchen: { x: 5.50, y: -2.40, yaw: 3.14 }
